# Generated by Django 5.0.3 on 2024-04-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Book_Combined',
        ),
    ]
