# Generated by Django 5.0.3 on 2024-06-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_customer_book_combined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_System_Users',
            fields=[
                ('library_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('library_user_email', models.EmailField(max_length=254, unique=True)),
                ('library_user_password', models.CharField(max_length=30)),
                ('library_user_username', models.CharField(max_length=30)),
                ('library_user_type', models.CharField(max_length=30)),
            ],
        ),
    ]
