# Generated by Django 5.0.3 on 2024-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_library_system_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_system_users',
            name='picture_upload',
            field=models.ImageField(default=True, upload_to='profile_picture'),
        ),
    ]
