# Generated by Django 5.0.3 on 2024-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_library_system_users_picture_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_system_users',
            name='picture_upload',
            field=models.ImageField(default=True, upload_to='profile_picture_library'),
        ),
    ]
